### ISSUE TITLE
possible omission of solutions

### ISSUE THREAD

**Issue by jaxfield** [lrghust/Seq-NMS#1]
Hi!
In the definition of findMaxPath, why is the loop in line 130 is the enumerate for roots rather than maxpaths?
I think roots delete the boxes that has no link with the boxes in the previous frame. However, such deleted boxes might has a high sum of score and a long link history and can be a good candidate for a good link. But maxpaths will not rule out such boxes. So do you think that enumerate the roots will cause the omission of feasible solution?

**Comment by ruigli** [comment]
Hi,
Thanks for your question.
Note that in def findMaxPath, the paths is extended from the last frame to the beginning. In each iteration, maxpaths records all possible paths so far on each box in current frame and the paths may 
continue to extend in next iteration, while the roots records path only when a path will no longer extend any more. What we want here is to find paths as long as possible, so we don't enumerate the maxpaths because it contains lots of unterminated paths. 
Treat all the boxes in frames as nodes in trees, the problem here can be viewed as to find seperate trees in the nodes with links. The roots will records all the seperate trees because when a path no longer extends, we reach a root of a tree. The maxpaths will records all the subtrees of trees in roots which are not what we want here.
